### ISSUE TITLE
Rotate character isn't necessary

### ISSUE THREAD

**Issue by Wedz0ff** [digonalha/tibia-runemaker#1]
This function should be removed on bot routine to avoid sending unnecessary keystrokes to client, because it's not necessary to rotate your character to avoid anti-afk.

**Comment by digonalha** [comment]
- [x] Criar um condicional para habilitar a rotação do personagem.  
- [x] Criar uma pergunta no padrão do método print_cabecalho

**Comment by digonalha** [comment]
done 👍
